[window.switch]
description = "Switch the current window"
match = """
  (switch | activate | focus) (the | to |) next window [direction=next]
  (switch | activate | focus) (the | to |) (previous | last) window [direction=back]
"""

[window.downloads]
description = "Open downloads"
match = """
  (show | open |) downloads (menu |)
"""

[window.exit]
description = "Closes the window"
match = """
  close (the |) (this |) (all |) (window{s}) (for me |)
"""

[[window.exit.example]]
phrase = "Close window"

[[window.exit.example]]
phrase = "Close this window"
text = true

[[window.exit.example]]
phrase = "Close all windows"
text = true
