[read.read]
description = "Narrate the given page. This puts the page into Reader Mode (failing if it can't) and starts narration"
match = """
  (can you |) read (me | ) (this | the |) (out content |) (article | articles | text |) (on this| )(tab | page |) (for me | to me |) (aloud |)
  read (me |) [query] (for me | to me |) (aloud |)
"""

[[read.read.example]]
phrase = "Read this page"

[[read.read.example]]
phrase = "Read out content to me"
test = true

[read.stopRead]
description = "Stop reading/narrating the current tab"
match = """
  stop reading (this |) (tab | page |) (to me | for me |)
"""

[[read.stopRead.example]]
phrase = "Stop reading"

[read.forwordRead]
description = "Forword reading/narrating"
match = """
  forword (this |) (tab | page |) (to me | for me |)
"""

[[read.forwordRead.example]]
phrase = "forword"

[[read.forwordRead.example]]
phrase = "forword this"

[read.backwordRead]
description = "Backword reading/narrating"
match = """
  backword (this |) (tab | page |) (to me | for me |)
"""
[[read.backwordRead.example]]
phrase = "backword"

[[read.backwordRead.example]]
phrase = "backword this"